variables:
  DOCKER_IMAGE: ${REGISTRY_URL}/${REGISTRY_PROJECT}/shoeshop:v1

stages:
  - buildandpush
  - deploy
  - checklog

buildandpush:
  stage: buildandpush
  variables:
    GIT_STRATEGY: clone
  before_script:
    - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  tags:
    - gitlab-server

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - chmod 400 ${KEY_PAIR}
    - echo "REGISTRY_URL=$REGISTRY_URL" >> .env
    - echo "REGISTRY_PROJECT=$REGISTRY_PROJECT" >> .env
    - echo "SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL" >> .env
    - echo "SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME" >> .env
    - echo "SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD" >> .env
    - scp -o StrictHostKeyChecking=no -i ${KEY_PAIR} docker-compose.yml .env ec2-user@${EC2_IP}:/home/ec2-user/
    - ssh -T -o StrictHostKeyChecking=no -i ${KEY_PAIR} ec2-user@${EC2_IP} "cd /home/ec2-user && docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} && docker-compose --env-file .env pull && docker-compose --env-file .env up -d"
  tags:
    - gitlab-server

checklog:
  stage: checklog
  variables:
    GIT_STRATEGY: none
  script:
    - sleep 20
    - chmod 400 ${KEY_PAIR}
    - ssh -T -o StrictHostKeyChecking=no -i ${KEY_PAIR} ec2-user@${EC2_IP} "docker compose logs shoeshop"
  tags:
    - gitlab-server
  only:
    - tags