version: "3.8"

services:

  shoeshop:
    image: ${REGISTRY_URL}/${REGISTRY_PROJECT}/shoeshop:v1
    container_name: shoeshop
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
